GET http://94.198.50.185:7081/api/users
Accept: application/json

@save session_id {{response.headers.Set-Cookie}}

<> 2023-11-16T140720.200.json
<> 2023-11-16T140614.200.json
<> 2023-11-16T140404.200.json
<> 2023-11-16T140357.200.json
<> 2023-11-16T121727.200.json

### Set-Cookie: JSESSIONID=3BF05738D510ECAD22D45618549530CF;
###
POST http://94.198.50.185:7081/api/users
Content-Type: application/json
Cookie: session={{session_id}}

{
  "id": 3,
  "name": "James",
  "lastName": "Brown",
  "age": 99
}

### Step 4: Update user with id = 3
PUT http://94.198.50.185:7081/api/users/3
Content-Type: application/json
Cookie: session={{session_id}}

{
  "name": "Thomas",
  "lastName": "Shelby"
}

### Step 5: Delete user with id = 3
DELETE http://94.198.50.185:7081/api/users/3
Cookie: session={{session_id}}